version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1
  gcp-gke: circleci/gcp-gke@1
  go: circleci/go@1
  k8s: circleci/kubernetes@0
  slack: circleci/slack@4

jobs:
  e2e:
    executor:
      name: go/default
      tag: '1.15'
    parameters:
      platform:
        type: string
        default: gke
    steps:
      - checkout
      - when:
          condition:
            or:
              - equal: [ gke, << parameters.platform >> ]
          steps:
            - gcp-gke/update-kubeconfig-with-credentials:
                perform-login: true
                cluster: $GOOGLE_CLUSTER_NAME
      - when:
          condition:
            or:
              - equal: [ eks, << parameters.platform >> ]
          steps:
            - aws-eks/update-kubeconfig-with-authenticator:
                cluster-name: $AWS_CLUSTER_NAME
                aws-region: $AWS_REGION
      - run:
          name: Running e2e tests
          environment:
            E2E_PASSTHROUGHS: "-e2e.kubeconfig=${HOME}/.kube/config"
          command: |
            make -C test/e2e e2e
      - slack/notify:
          event: always
          branch_pattern: unparallelize-test
          mentions: "@sameersbn"
          channel: 'C020PQRC867'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: Your job *${CIRCLE_PROJECT_REPONAME}/${CIRCLE_JOB}* has failed :bomb:cc ${SLACK_PARAM_MENTIONS}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Commit"
                      },
                      "url": "https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}"
                    }
                  ]
                }
              ]
            }

workflows:
  version: 2

  staging:
    jobs:
      - e2e:
          name: e2e-staging
          context: staging
          platform: eks

  staging-nightly:
    jobs:
      - e2e:
          name: e2e-staging-nightly
          context: staging
          platform: eks
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - unparallelize-test

  prod:
    jobs:
      - e2e:
          name: e2e-prod
          context: production
          platform: gke

  prod-nightly:
    jobs:
      - e2e:
          name: e2e-prod-nightly
          context: production
          platform: gke
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - unparallelize-test
