version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  k8s: circleci/kubernetes@0.11.0
  go: circleci/go@1.4.0

jobs:
  e2e:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/mod-download-cached
      - gcp-gke/update-kubeconfig-with-credentials:
          perform-login: true
          cluster: $GOOGLE_CLUSTER_NAME
      - run:
          name: Running e2e tests
          command: |
            E2E_PASSTHROUGHS="-e2e.kubeconfig=${HOME}/.kube/config" make e2e

workflows:
  version: 2

  staging:
    jobs:
      - e2e:
          context: staging

  prod:
    jobs:
      - e2e:
          context: production

  staging-nightly:
    jobs:
      - e2e:
          context: staging
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

  prod-nightly:
    jobs:
      - e2e:
          context: production
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
